
GET http://localhost:8080/demo/all

###

POST http://localhost:8080/demo/add
Content-Type: application/x-www-form-urlencoded

name=Jefferson Cerrón
&email=PT18459623@idat.edu.pe
###

GET http://localhost:8080/demo/ver/2

###

PUT http://localhost:8080/demo/edit
Content-Type: application/x-www-form-urlencoded

id=2
&name=Jefferson Limaylla
&email=Jeff@idat.edu.pe

###

DELETE http://localhost:8080/demo/del
Content-Type: application/x-www-form-urlencoded

id=204

###

GET http://localhost:8080/demo/get/report

